import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { paths } from "@amem/core";

const HEADER = `# generated by amem compile — do not edit\n# source: amem capabilities\n\n`;

export type CompileTarget = "cursor" | "claude-code" | "dsh";

export type SkillRow = {
  name: string;
  version: string;
  hasSkillMd: boolean;
  description: string;
};

export type ProposalRow = {
  id: string;
  hasProposalMd: boolean;
  title: string;
};

export function listSkillsData(home: string): SkillRow[] {
  const dir = join(paths(home).capabilities, "skills");
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()
    .map((name) => {
      const skillMd = join(dir, name, "SKILL.md");
      const capYaml = join(dir, name, "capability.yaml");
      let version = "-";
      let description = "";
      if (existsSync(capYaml)) {
        const text = readFileSync(capYaml, "utf8");
        const vm = text.match(/^version:\s*(.+)$/m);
        if (vm) version = vm[1]!.trim();
      }
      if (existsSync(skillMd)) {
        const text = readFileSync(skillMd, "utf8");
        const dm = text.match(/^description:\s*(.+)$/m);
        if (dm) description = dm[1]!.trim();
      }
      return {
        name,
        version,
        hasSkillMd: existsSync(skillMd),
        description,
      };
    });
}

export function listProposalsData(home: string): ProposalRow[] {
  const dir = join(paths(home).capabilities, ".proposals");
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()
    .map((id) => {
      const skill = join(dir, id, "SKILL.md");
      const proposal = join(dir, id, "proposal.md");
      let title = id;
      if (existsSync(skill)) {
        const text = readFileSync(skill, "utf8");
        const nm = text.match(/^name:\s*(.+)$/m) || text.match(/^description:\s*(.+)$/m);
        if (nm) title = nm[1]!.trim();
      }
      return {
        id,
        hasProposalMd: existsSync(proposal),
        title,
      };
    });
}

function destForTarget(target: CompileTarget, outRoot?: string): string {
  if (outRoot) return outRoot;
  if (target === "cursor") return join(homedir(), ".cursor", "skills");
  if (target === "dsh") return join(homedir(), ".dsh", "skills");
  return join(homedir(), ".claude", "skills");
}

export function compileCapabilities(
  home: string,
  target: CompileTarget,
  outRoot?: string,
): { written: string[] } {
  const capRoot = paths(home).capabilities;
  const skillsDir = join(capRoot, "skills");
  const written: string[] = [];
  if (!existsSync(skillsDir)) return { written };

  const destBase = destForTarget(target, outRoot);

  for (const name of readdirSync(skillsDir)) {
    const src = join(skillsDir, name, "SKILL.md");
    if (!existsSync(src)) continue;
    const body = readFileSync(src, "utf8");
    const destDir = join(destBase, name);
    mkdirSync(destDir, { recursive: true });
    const dest = join(destDir, "SKILL.md");
    if (existsSync(dest)) {
      const prev = readFileSync(dest, "utf8");
      if (!prev.includes("generated by amem compile") && prev !== body) {
        throw new Error(`refusing to overwrite hand-edited skill: ${dest}`);
      }
    }
    writeFileSync(dest, HEADER + body);
    written.push(dest);
  }

  return { written };
}

export function materializeProposal(home: string, proposalId: string, skillName: string): string {
  const src = join(paths(home).capabilities, ".proposals", proposalId, "SKILL.md");
  if (!existsSync(src)) throw new Error(`proposal not found: ${proposalId}`);
  const destDir = join(paths(home).capabilities, "skills", skillName);
  mkdirSync(destDir, { recursive: true });
  const dest = join(destDir, "SKILL.md");
  writeFileSync(dest, readFileSync(src, "utf8"));
  writeFileSync(
    join(destDir, "capability.yaml"),
    `id: ${skillName}\nversion: 0.1.0\nstatus: active\nsource_proposal: ${proposalId}\n`,
  );
  return dest;
}
